name: Publish Resume
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/flake.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build Resume with Nix
        run: nix build .#defaultPackage.x86_64-linux
      - name: Clone Copy of Publish Branch Locally
        run: git clone -b publish https://github.com/ChristopherJMiller/Resume.git ../Publish
      - name: Move Payload into New Branch
        run: sudo mv result/resume.pdf ../Publish/resume.pdf
      - name: Check Work
        run: ls -l ../Publish
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit
        run: |
          cd ../Publish
          git add -A resume.pdf
          git commit -m "Publish Resume"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ../Publish
          branch: publish
